name: Cypress Tests

on:
  [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          npm-version: '7'

      - name: Update npm and clear cache
        run: |
          npm install -g npm@latest
          npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress component tests
        run: npx cypress run-ct
  linkinator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your code

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: Install Linkinator
        run: npm install -g linkinator

      - name: Run Linkinator
        run: linkinator https://sft.gildlab.xyz/  # Replace with your desired URL