name: Cypress Tests
on:
  [push]
jobs:
  cypress-component-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          npm-version: '10'
      - name: Update npm and clear cache
        run: |
          npm install -g npm@latest
          npm cache clean --force
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress component tests
        run: npx cypress run-ct
  cypress-e2e-tests:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: 'https://lucky-poetry-9761.on.fleek.co'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install wait-on with npm
        run: npm install wait-on
      - name: Install Cypress with npm
        run: npm install cypress
      - name: Update npm and clear cache
        run: |
          npm install -g npm@latest
          npm cache clean --force
      - name: Install project dependencies with npm
        run: npm ci

      - name: Run Cypress E2E tests
        run: |
          npx cypress run
      - name: Debug Information
        run: |
          echo "CYPRESS_BASE_URL: $CYPRESS_BASE_URL"
          # Add more debugging commands as needed