name: Linkinator

on:
  [ push ]

jobs:
  linkinator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Linkinator
        run: npm install -g linkinator

      - name: Run Linkinator
        run: linkinator https://sft.gildlab.xyz/
